-- Sirus Lib (Core Library)
"names": {
"legsplab": "Offshore Seaplane Platform",
"legspcon": "Construction Seaplane",
"legspsurfacegunship": "Enyo",
"legspcarrier": "Hecatoncheir",
"legspbomber": "Pyrphoros",
"legsptorpgunship": "Ladon",
"legspfighter": "Astrapios",
"legspradarsonarplane": "Okeanos",
"leganavyaaship": "Notus",
"leganavyantinukecarrier": "Hecate",
"leganavyartyship": "Corinth",
"leganavybattleship": "Scylla",
"leganavyconsub": "Advanced Construction Submarine",
"leganavycruiser": "Thalassa",
"leganavyengineer": "Artifex",
"leganavyflagship": "Neptune",
"leganavymissileship": "Ultor",
"leganavyradjamship": "Dolus",
"leganavyantiswarm": "Leocampus",
"leganavybattlesub": "Architeuthis",
"leganavyheavysub": "Sphyrna",
"leganavalaaturret": "Fulmen",
"leganavaltorpturret": "Delphinus",
"leganavaladvgeo": "Advanced Underwater Geomthermal Powerplant",
"leganavalfusion": "Naval Fusion Reactor",
"leganavalmex": "Advanced Underwater Metal Extractor",
"leganavalpinpointer": "Naval Pinpointer",
"leganavalsonarstation": "Auscultor",
"legadvshipyard": "Advanced Shipyard",
"armaak": "Archangel",
"armaap": "Advanced Aircraft Plant",
"armaas": "Dragonslayer",
"armaca": "Advanced Construction Aircraft",
"armack": "Advanced Construction Bot",
"armacsub": "Advanced Construction Sub",
"armacv": "Advanced Construction Vehicle",
"armadvsol": "Advanced Solar Collector",
"armafus": "Advanced Fusion Reactor",
"armafust3": "Epic Fusion Reactor",
"armageo": "Advanced Geothermal Powerplant",
"armah": "Sweeper",
"armalab": "Advanced Bot Lab",
"armamb": "Rattlesnake",
"armamd": "Citadel",
"armamex": "Twilight",
"armamph": "Platypus",
"armamsub": "Amphibious Complex",
"armanac": "Crocodile",
"armanavaldefturret": "Liquifier",
"armanni": "Pulsar",
"armannit3": "Epic Pulsar",
"armantiship": "Haven",
"armap": "Aircraft Plant",
"armapt3": "Experimental Aircraft Plant",
"armarad": "Advanced Radar Tower",
"armart": "Shellshocker",
"armaser": "Smuggler",
"armason": "Advanced Sonar Station",
"armassimilator": "Assimilator",
"armassistdrone": "Assist Drone",
"armassistdrone_land": "Assist Vehicle",
"armasy": "Advanced Shipyard",
"armatl": "Moray",
"armatlas": "Stork",
"armavp": "Advanced Vehicle Plant",
"armawac": "Oracle",
"armbanth": "Titan",
"armbats": "Dreadnought",
"armbeamer": "Beamer",
"armbeaver": "Beaver",
"armblade": "Hornet",
"armbotrail": "Pawn Launcher",
"armbrawl": "Roughneck",
"armbrtha": "Basilica",
"armbull": "Bull",
"armca": "Construction Aircraft",
"armcarry": "Haven",
"armch": "Construction Hovercraft",
"armcir": "Chainsaw",
"armck": "Construction Bot",
"armckfus": "Cloakable Fusion Reactor",
"armclaw": "Dragon's Claw",
"armcom": "Armada Commander",
"armcomboss": "Epic Commander - Final Boss",
"armcomlvl10": "Armada Commander Level 10",
"armcomlvl2": "Armada Commander Level 2",
"armcomlvl3": "Armada Commander Level 3",
"armcomlvl4": "Armada Commander Level 4",
"armcomlvl5": "Armada Commander Level 5",
"armcomlvl6": "Armada Commander Level 6",
"armcomlvl7": "Armada Commander Level 7",
"armcomlvl8": "Armada Commander Level 8",
"armcomlvl9": "Armada Commander Level 9",
"armconsul": "Consul",
"armcroc": "Turtle",
"armcrus": "Paladin",
"armcs": "Construction Ship",
"armcsa": "Construction Seaplane",
"armcv": "Construction Vehicle",
"armdecade": "Dolphin",
"armdecadet3": "Epic Dolphin",
"armdecom": "Commander",
"armdf": "Decoy Fusion Reactor",
"armdfly": "Abductor",
"armdl": "Anemone",
"armdrag": "Dragon's Teeth",
"armdrone": "Attack Drone",
"armdronecarry": "Nexus",
"armdronecarryland": "Nexus Terra",
"armdroneold": "Attack Drone",
"armemp": "Paralyzer",
"armepoch": "Epoch",
"armestor": "Energy Storage",
"armexcalibur": "Excalibur",
"armeyes": "Beholder",
"armfark": "Butler",
"armfast": "Sprinter",
"armfatf": "Naval Pinpointer",
"armfav": "Rover",
"armfboy": "Fatboy",
"armfdrag": "Shark's Teeth",
"armfepocht4": "Flying Epoch",
"armferret": "Ferret",
"armfflak": "Naval Arbalest",
"armfgate": "Aurora",
"armfhlt": "Manta",
"armfhp": "Naval Hovercraft Platform",
"armfido": "Hound",
"armfify":"Firefly",
"armfig": "Falcon",
"armflak": "Arbalest",
"armflash": "Blitz",
"armflea": "Tick",
"armfmine3": "Heavy Mine",
"armfmkr": "Naval Energy Converter",
"armfort": "Fortification Wall",
"armfrad": "Naval Radar / Sonar Tower",
"armfrock": "Scumbag",
"armfrt": "Naval Nettle",
"armfus": "Fusion Reactor",
"armgate": "Keeper",
"armgatet3": "Asylum",
"armgeo": "Geothermal Powerplant",
"armgmm": "Prude",
"armgplat": "Gun Platform",
"armgremlin": "Gremlin",
"armguard": "Gauntlet",
"armhaap": "Experimental Aircraft Plant",
"armhaapuw": "Advanced Aircraft Plant",
"armhaca": "Experimental Construction Aircraft",
"armhack": "Butler",
"armhacs": "Voyager",
"armhacv": "Consul",
"armhalab": "Experimental Bot Lab",
"armham": "Mace",
"armhasy": "Experimental Shipyard",
"armhavp": "Experimental Vehicle Plant",
"armhawk": "Highwind",
"armhlt": "Overwatch",
"armhp": "Hovercraft Platform",
"armhvytrans": "Osprey",
"armjam": "Umbra",
"armjamt": "Sneaky Pete",
"armjanus": "Janus",
"armjeth": "Crossbow",
"armjuno": "Juno",
"armkam": "Banshee",
"armkraken": "Gorgon",
"armlab": "Bot Lab",
"armlance": "Cormorant",
"armlatnk": "Jaguar",
"armliche": "Liche",
"armlichet4": "Epic Liche",
"armllt": "Sentry",
"armlship": "Maelstrom",
"armlun": "Lunkhead",
"armlunchbox": "Lunchbox",
"armlwall": "Dragon's Fury",
"armmakr": "Energy Converter",
"armmanni": "Starlight",
"armmar": "Marauder",
"armmark": "Compass",
"armmart": "Mauser",
"armmav": "Gunslinger",
"armmeatball": "Meatball",
"armmercury": "Mercury",
"armmerl": "Ambassador",
"armmex": "Metal Extractor",
"armmh": "Possum",
"armmine1": "Light Mine",
"armmine2": "Medium Mine",
"armmine3": "Heavy Mine",
"armminivulc": "Mini Ragnarok",
"armmls": "Voyager",
"armmlv": "Groundhog",
"armmmkr": "Advanced Energy Converter",
"armmmkrt3": "Epic Energy Converter",
"armmoho": "Advanced Metal Extractor",
"armmship": "Longbow",
"armmstor": "Metal Storage",
"armnanotc": "Construction Turret",
"armnanotc2plat": "Advanced Construction Turret",
"armnanotcplat": "Naval Construction Turret",
"armnanotct2": "Advanced Construction Turret",
"armnavaldefturret": "Cauteriser",
"armpb": "Pit Bull",
"armpeep": "Blink",
"armpincer": "Pincer",
"armplat": "Seaplane Platform",
"armpnix": "Blizzard",
"armpship": "Ellysaw",
"armpshipt3": "Epic Ellysaw",
"armpt": "Skater",
"armptt2": "Epic Skater",
"armpw": "Pawn",
"armpwt4": "Epic Pawn",
"armrad": "Radar Tower",
"armrattet4": "Ratte",
"armraz": "Razorback",
"armrecl": "Grim Reaper",
"armrectr": "Lazarus",
"armrectrt4": "Epic Rector",
"armrespawn": "Base Builder",
"armrl": "Nettle",
"armrock": "Rocketeer",
"armroy": "Corsair",
"armsaber": "Sabre",
"armsam": "Whistler",
"armsat": "Satellite",
"armsb": "Tsunami",
"armscab": "Umbrella",
"armscavengerbossv2": "Epic Commander - Final Boss",
"armsd": "Tracer",
"armseadragon": "Seadragon",
"armseap": "Puffin",
"armseer": "Prophet",
"armsehak": "Horizon",
"armserp": "Serpent",
"armserpt3": "Epic Serpent",
"armsfig": "Cyclone",
"armsfig2": "Cyclone",
"armsh": "Seeker",
"armshltx": "Experimental Gantry",
"armshltxuw": "Experimental Gantry",
"armshockwave": "Shockwave",
"armsilo": "Armageddon",
"armsjam": "Bermuda",
"armsnipe": "Sharpshooter",
"armsolar": "Solar Collector",
"armsonar": "Sonar Station",
"armspid": "Webber",
"armsptk": "Recluse",
"armsptkt4": "Epic Recluse",
"armspy": "Ghost",
"armstil": "Stiletto",
"armstump": "Stout",
"armsub": "Eel",
"armsubk": "Barracuda",
"armsy": "Shipyard",
"armtarg": "Pinpointer",
"armtdrone": "Depth Charge Drone",
"armthor": "Thor",
"armthovr": "Bearer",
"armthund": "Stormbringer",
"armthundt4": "Epic Stormbringer",
"armtide": "Tidal Generator",
"armtl": "Harpoon",
"armtorps": "Torpedo Ship",
"armtrident": "Trident",
"armtship": "Convoy",
"armuwadves": "Hardened Energy Storage",
"armuwadvms": "Hardened Metal Storage",
"armuwageo": "Advanced Geothermal Powerplant",
"armuwes": "Naval Energy Storage",
"armuwfus": "Naval Fusion Reactor",
"armuwgeo": "Offshore Geothermal Powerplant",
"armuwmme": "Naval Advanced Metal Extractor",
"armuwmmm": "Naval Advanced Energy Converter",
"armuwms": "Naval Metal Storage",
"armvader": "Tumbleweed",
"armvadert4": "Epic Tumbleweed",
"armvang": "Vanguard",
"armveil": "Veil",
"armvp": "Vehicle Plant",
"armvulc": "Ragnarok",
"armwar": "Centurion",
"armwin": "Wind Turbine",
"armwint2": "Advanced Wind Turbine",
"armyork": "Shredder",
"armzapper": "Zapper",
"armzeus": "Welder",
"chip": "Chip",
"comeffigy": "Commander Effigy",
"cor_hat_fightnight": "#1 Grunt",
"cor_hat_hornet": "Hornet's Tricorn",
"cor_hat_hw": "Spooky Pumpkin",
"cor_hat_legfn": "#1 Goblin",
"cor_hat_ptaq": "PtaQ's Hat",
"cor_hat_viking": "Viking Helmet",
"coraak": "Manticore",
"coraap": "Advanced Aircraft Plant",
"coraca": "Advanced Construction Aircraft",
"corack": "Advanced Construction Bot",
"coracsub": "Advanced Construction Sub",
"coracv": "Advanced Construction Vehicle",
"coradvsol": "Advanced Solar Collector",
"corafus": "Advanced Fusion Reactor",
"corafust3": "Epic Fusion Reactor",
"corageo": "Advanced Geothermal Powerplant",
"corah": "Birdeater",
"corak": "Grunt",
"corakt4": "Epic Grunt",
"coralab": "Advanced Bot Lab",
"coramph": "Duck",
"coramsub": "Amphibious Complex",
"coranavaldefturret": "Orthrus",
"corantiship": "Oasis",
"corap": "Aircraft Plant",
"corape": "Wasp",
"corapt3": "Experimental Aircraft Plant",
"corarad": "Advanced Radar Tower",
"corarch": "Arrow Storm",
"corason": "Advanced Sonar Station",
"corassistdrone": "Assist Drone",
"corassistdrone_land": "Assist Vehicle",
"corasy": "Advanced Shipyard",
"coratl": "Lamprey",
"coravp": "Advanced Vehicle Plant",
"corawac": "Condor",
"corban": "Banisher",
"corbats": "Despot",
"corbhmth": "Cerberus",
"corblackhy": "Black Hydra",
"corbuzz": "Calamity",
"corbw": "Shuriken",
"corca": "Construction Aircraft",
"corcan": "Sumo",
"corcarry": "Oasis",
"corcat": "Catapult",
"corch": "Construction Hovercraft",
"corck": "Construction Bot",
"corcom": "Cortex Commander",
"corcomboss": "Epic Commander - Final Boss",
"corcomlvl10": "Cortex Commander Level 10",
"corcomlvl2": "Cortex Commander Level 2",
"corcomlvl3": "Cortex Commander Level 3",
"corcomlvl4": "Cortex Commander Level 4",
"corcomlvl5": "Cortex Commander Level 5",
"corcomlvl6": "Cortex Commander Level 6",
"corcomlvl7": "Cortex Commander Level 7",
"corcomlvl8": "Cortex Commander Level 8",
"corcomlvl9": "Cortex Commander Level 9",
"corcrash": "Trasher",
"corcrus": "Buccaneer",
"corcrw": "Archaic Dragon",
"corcrwh": "Dragon",
"corcrwt4": "Epic Dragon",
"corcs": "Construction Ship",
"corcsa": "Construction Seaplane",
"corcut": "Cutlass",
"corcv": "Construction Vehicle",
"cordeadeye": "Deadeye",
"cordecom": "Commander",
"cordemon": "Demon",
"cordesolator": "Desolator",
"cordl": "Jellyfish",
"cordoom": "Bulwark",
"cordoomt3": "Epic Bulwark",
"cordrag": "Dragon's Teeth",
"cordrone": "Attack Drone",
"cordronecarry": "Disperser",
"cordronecarryair": "Disperser Omni",
"cordroneold": "Attack Drone",
"cords": "Disgruntler",
"corenaa": "Naval Birdshot",
"corerad": "Eradicator",
"corestor": "Energy Storage",
"coresupp": "Supporter",
"coresuppt3": "Adjudicator",
"coreter": "Obscurer",
"corexp": "Exploiter",
"coreyes": "Beholder",
"corfast": "Twitcher",
"corfatf": "Naval Pinpointer",
"corfav": "Rascal",
"corfblackhyt4": "Flying Black Hydra",
"corfdoom": "Devastator",
"corfdrag": "Shark's Teeth",
"corfgate": "Atoll",
"corfhlt": "Coral",
"corfhp": "Naval Hovercraft Platform",
"corfink": "Finch",
"corflak": "Birdshot",
"corfmd": "Prevailer",
"corfmine3": "Heavy Mine",
"corfmkr": "Naval Energy Converter",
"corforge": "Forge",
"corfort": "Fortification Wall",
"corfrad": "Naval Radar / Sonar Tower",
"corfrock": "Janitor",
"corfrt": "Slingshot",
"corfship": "Brimstone",
"corftiger": "Heat Tiger",
"corfus": "Fusion Reactor",
"corgant": "Experimental Gantry",
"corgantuw": "Experimental Gantry",
"leggantuw": "Experimental Gantry",
"corgarp": "Garpike",
"corgate": "Overseer",
"corgatet3": "Sanctuary",
"corgator": "Incisor",
"corgatreap": "Laser Tiger",
"corgeo": "Geothermal Powerplant",
"corgol": "Tzar",
"corgolt4": "Epic Tzar",
"corgplat": "Gun Platform",
"corhaap": "Experimental Aircraft Plant",
"corhaapuw": "Advanced Aircraft Plant",
"corhaca": "Experimental Construction Aircraft",
"corhack": "Twitcher",
"corhacs": "Pathfinder",
"corhacv": "Printer",
"corhal": "Halberd",
"corhalab": "Experimental Bot Lab",
"corhasy": "Experimental Shipyard",
"corhavp":"Experimental Vehicle Plant",
"corhllllt": "Quad Guard",
"corhllt": "Twin Guard",
"corhlt": "Warden",
"corhp": "Hovercraft Platform",
"corhrk": "Arbiter",
"corhunt": "Watcher",
"corhurc": "Hailstorm",
"corhvytrans": "Hephaestus",
"corint": "Basilisk",
"corintr": "Intruder",
"corjamt": "Castro",
"corjugg": "Behemoth",
"corjuno": "Juno",
"corkarg": "Karganeth",
"corkarganetht4": "Epic Karganeth",
"corkark": "Archaic Karkinos",
"corkorg": "Juggernaut",
"corlab": "Bot Lab",
"corlevlr": "Pounder",
"corllt": "Guard",
"cormabm": "Saviour",
"cormadsam": "SAM",
"cormakr": "Energy Converter",
"cormando": "Commando",
"cormandot4": "Epic Commando",
"cormart": "Quaker",
"cormaw": "Dragon's Maw",
"cormex": "Metal Extractor",
"cormexp": "Advanced Exploiter",
"cormh": "Mangonel",
"cormine1": "Light Mine",
"cormine2": "Medium Mine",
"cormine3": "Heavy Mine",
"cormine4": "Medium Mine",
"corminibuzz": "Mini Calamity",
"cormist": "Lasher",
"cormls": "Pathfinder",
"cormlv": "Trapper",
"cormmkr": "Advanced Energy Converter",
"cormmkrt3": "Epic Energy Converter",
"cormoho": "Advanced Metal Extractor",
"cormort": "Sheldon",
"cormship": "Messenger",
"cormstor": "Metal Storage",
"cormuskrat": "Muskrat",
"cormwall": "Dragon's Rage",
"cornanotc": "Construction Turret",
"cornanotc2plat": "Advanced Construction Turret",
"cornanotcplat": "Naval Construction Turret",
"cornanotct2": "Advanced Construction Turret",
"cornavaldefturret": "Cyclops",
"cornecro": "Graverobber",
"coronager": "Onager",
"corparrow": "Poison Arrow",
"corphantom": "Phantom",
"corplat": "Seaplane Platform",
"corprince": "Black Prince",
"corprinter": "Printer",
"corpship": "Riptide",
"corpt": "Herring",
"corpun": "Agitator",
"corpyro": "Fiend",
"corrad": "Radar Tower",
"corraid": "Brute",
"correap": "Tiger",
"correcl": "Death Cavalry",
"correspawn": "Base Builder",
"corrl": "Thistle",
"corroach": "Bedbug",
"corroy": "Oppressor",
"corsala": "Salamander",
"corsat": "Satellite",
"corsb": "Dam Buster",
"corscavdrag": "Dragon's Teeth",
"corscavdtf": "Dragon's Maw",
"corscavdtl": "Dragon's Claw",
"corscavdtm": "Missile Wall",
"corscavfort": "Fortification Wall",
"corscreamer": "Screamer",
"corsd": "Nemesis",
"corseah": "Skyhook",
"corseal": "Alligator",
"corseap": "Monsoon",
"corsent": "Fury",
"corsentinel": "Sentinel",
"corsfig": "Bat",
"corsfig2": "Bat",
"corsh": "Goon",
"corshad": "Whirlwind",
"corshark": "Predator",
"corshiva": "Shiva",
"corshroud": "Shroud",
"corsiegebreaker": "Siegebreaker",
"corsilo": "Apocalypse",
"corsjam": "Phantasm",
"corsktl": "Skuttle",
"corslrpc": "Leviathan",
"corsnap": "Cayman",
"corsok": "Cataphract",
"corsolar": "Solar Collector",
"corsonar": "Sonar Station",
"corspec": "Deceiver",
"corspy": "Spectre",
"corssub": "Kraken",
"corstorm": "Aggravator",
"corsub": "Orca",
"corsumo": "Mammoth",
"corsy": "Shipyard",
"cortarg": "Pinpointer",
"cortdrone": "Depth Charge Drone",
"cortermite": "Termite",
"corthermite": "Thermite",
"corthovr": "Caravan",
"corthud": "Thug",
"cortide": "Tidal Generator",
"cortitan": "Angler",
"cortl": "Urchin",
"cortoast": "Persecutor",
"cortorch": "Torch",
"cortrem": "Tremor",
"cortron": "Catalyst",
"cortship": "Coffin",
"coruwadves": "Hardened Energy Storage",
"coruwadvms": "Hardened Metal Storage",
"coruwageo": "Advanced Geothermal Powerplant",
"coruwes": "Naval Energy Storage",
"coruwfus": "Naval Fusion Reactor",
"coruwgeo": "Offshore Geothermal Powerplant",
"coruwmme": "Naval Advanced Metal Extractor",
"coruwmmm": "Naval Advanced Energy Converter",
"leganavaleconv": "Naval Advanced Energy Converter",
"coruwms": "Naval Metal Storage",
"corvac": "Printer",
"corvalk": "Hercules",
"corvamp": "Nighthawk",
"corveng": "Valiant",
"corvipe": "Scorpion",
"corvoyr": "Augur",
"corvp": "Vehicle Plant",
"corvrad": "Omen",
"corvroc": "Negotiator",
"corwin": "Wind Turbine",
"corwint2": "Advanced Wind Turbine",
"corwolv": "Wolverine",
"critter_ant": "Ant",
"critter_crab": "Crab",
"critter_duck": "Duck",
"critter_goldfish": "Goldfish",
"critter_gull": "Seagull",
"critter_penguin": "Penguin",
"critter_penguinbro": "Penguin Bro",
"critter_penguinking": "Penguin King",
"dbg_sphere": "dbg_sphere",
"dbg_sphere_fullmetal": "dbg_sphere",
"dice": "Dice",
"freefusion": "Free Fusion Reactor",
"leegmech": "Praetorian",
"legaabot": "Toxotai",
"legaap": "Legion Advanced Aircraft Plant",
"legabm": "Aegis",
"legaca": "Advanced Construction Aircraft",
"legaceb": "Proteus",
"legack": "Advanced Construction Bot",
"legacluster": "Eviscerator",
"legacv": "Advanced Construction Vehicle",
"legadvaabot": "Aquilon",
"legadveconv": "Advanced Energy Converter",
"legadveconvt3": "Epic Energy Converter",
"legadvestore": "Hardened Energy Storage",
"legadvsol": "Advanced Solar Collector",
"legafcv": "Aceso",
"legafigdef": "Ajax",
"legafus": "Advanced Fusion Reactor",
"legafust3": "Epic Fusion Reactor",
"legageo": "Advanced Geothermal Powerplant",
"legah": "Alpheus",
"legaheattank": "Prometheus",
"legajam": "Erebus",
"legajamk": "Tiresias",
"legalab": "Legion Advanced Bot Lab",
"legamcluster": "Cleaver",
"legamph": "Telchine",
"legamphlab": "Amphibious Complex",
"legamphtank": "Cetus",
"legamstor": "Hardened Metal Storage",
"leganavaldefturret": "Ionia",
"legap": "Legion Drone Plant",
"legapopupdef": "Chimera",
"legapt3": "Experimental Aircraft Gantry",
"legarad": "Advanced Radar Tower",
"legaradk": "Euclid",
"legaskirmtank": "Gladiator",
"legaspy": "Eidolon",
"legassistdrone": "Assist Drone",
"legassistdrone_land": "Assist Vehicle",
"legatorpbomber": "Aesacus",
"legatrans": "Hippotes",
"legavjam": "Cicero",
"legavp": "Advanced Vehicle Plant",
"legavrad": "Pheme",
"legavroc": "Boreas",
"legbal": "Ballista",
"legbar": "Barrage",
"legbart": "Belcher",
"legbastion": "Bastion",
"legbombard": "Bombardier",
"legbunk": "Pilum",
"legca": "Legion Construction Aircraft",
"legcar": "Cardea",
"legcen": "Phobos",
"legch": "Construction Hovercraft",
"legcib": "Blindfold",
"legck": "Legion Construction Bot",
"legcluster": "Amputator",
"legcom": "Legion Commander",
"legcomdef": "Defensive Commander",
"legcomecon": "Economy Commander",
"legcomlvl10": "Legion Commander Level 10",
"legcomlvl2": "Legion Commander Level 2",
"legcomlvl3": "Legion Commander Level 3",
"legcomlvl4": "Legion Commander Level 4",
"legcomlvl5": "Legion Commander Level 5",
"legcomlvl6": "Legion Commander Level 6",
"legcomlvl7": "Legion Commander Level 7",
"legcomlvl8": "Legion Commander Level 8",
"legcomlvl9": "Legion Commander Level 9",
"legcomoff": "Offensive Commander",
"legcomt2com": "Combat Commander",
"legcomt2def": "Tactical Defense Commander",
"legcomt2off": "Tactical Offense Commander",
"legctl": "Euryale",
"legcv": "Legion Construction Vehicle",
"legdecom": "Legion Commander",
"legdeflector": "Soteria",
"legdrag": "Dragon's Teeth",
"legdrone": "Legion Drone",
"legdtf": "Dragon's Maw",
"legdtl": "Dragon's Claw",
"legdtm": "Dragon's Tail",
"legdtr": "Dragon's Jaw",
"legeallterrainmech": "Myrmidon",
"legeconv": "Energy Converter",
"legeheatraymech": "Sol Invictus",
"legeheatraymech_old": "Archaic Sol Invictus",
"legehovertank": "Charybdis",
"legelrpcmech": "Astraeus",
"legerailtank": "Daedalus",
"legeshotgunmech": "Praetorian",
"legestor": "Energy Storage",
"legeyes": "Argus",
"legfdrag": "Shark's Teeth",
"legfeconv": "Naval Energy Converter",
"legfhive": "Hive",
"legfhp": "Offshore Hovercraft Platform",
"legfig": "Noctua",
"legflak": "Pluto",
"legfloat": "Triton",
"legfmg": "Gelasma",
"legfmkr": "Naval Energy Converter",
"legfort": "Tyrannus",
"legforti": "Fortification Wall",
"legfortt4": "Epic Tyrannus",
"legfrad": "Naval Radar / Sonar Tower",
"legfrl": "Polybolos",
"legfus": "Fusion Reactor",
"leggant": "Experimental Gantry",
"leggat": "Decurion",
"leggatet3": "Elysium",
"leggeo": "Geothermal Powerplant",
"leggob": "Goblin",
"leggobt3": "Epic Goblin",
"leghaap": "Legion Experimental Aircraft Plant",
"leghaca": "Experimental Construction Aircraft",
"leghack": "Prometheus",
"leghacv": "Aceso",
"leghades": "Alaris",
"leghalab": "Experimental Bot Lab",
"leghastatus": "Hastatus",
"leghastatusalt": "Hastatus",
"leghavp": "Experimental Vehicle Plant",
"legheavydrone": "Legion Heavy Drone",
"legheavydronesmall": "Legion Heavy Drone",
"leghelios": "Helios",
"leghive": "Hive",
"leghp": "Hovercraft Platform",
"leghrk": "Thanatos",
"leginc": "Incinerator",
"leginf": "Inferno",
"leginfestor": "Infestor",
"legionnaire": "Legionnaire",
"legjam": "Nyx",
"legjav": "Javelin",
"legjim": "Shipyard",
"legjuno": "Juno",
"legkam": "Martyr",
"legkark": "Karkinos",
"legkeres": "Keres",
"leglab": "Legion Bot Lab",
"leglht": "Pharos",
"leglob": "Satyr",
"leglraa": "Xyston",
"leglrpc": "Olympus",
"leglts": "Aeolus",
"leglupara": "Lupara",
"legmed": "Medusa",
"legmex": "Metal Extractor",
"legmext15": "Overcharged Metal Extractor",
"legmg": "Cacophony",
"legmh": "Salacia",
"legmine1": "Light Mine",
"legmine2": "Medium Mine",
"legmine3": "Heavy Mine",
"legmineb": "Harbinger",
"legministarfall": "Mini Starfall",
"legmlv": "Sapper",
"legmoho": "Advanced Metal Extractor",
"legmohobp": "Fortifier",
"legmohocon": "Advanced Metal Fortifier",
"legmohoconct": "Advanced Metal Fortifier",
"legmohoconin": "Advanced Metal Fortifier",
"legmos": "Mosquito",
"legmost3": "Epic Mosquito",
"legmrv": "Quickshot",
"legmstor": "Metal Storage",
"legnanotc": "Construction Turret",
"legnanotcbase": "Base Builder",
"legnanotcplat": "Naval Construction Turret",
"legnanotct2": "Advanced Construction Turret",
"legnanotct2plat": "Advanced Construction Turret",
"legnap": "Wildfire",
"legnavaldefturret": "Phorcys",
"legnavyaaship": "Iapetus",
"legnavyartyship": "Octeres",
"legnavyconship": "Construction Ship",
"legnavydestro": "Syracusia",
"legnavyfrigate": "Argonaut",
"legnavyrezsub": "Dionysus",
"legnavyscout": "Hippocampus",
"legnavysub": "Ketea",
"legner": "Nereus",
"legoptio": "Optio",
"legotter": "Otter",
"legpede": "Mukade",
"legperdition": "Perdition",
"legphoenix": "Phoenix",
"legpontus": "Pontus",
"legportent": "Portent",
"legrad": "Radar Tower",
"legrail": "Lance",
"legrampart": "Rampart",
"legrezbot": "Zagreus",
"legrhapsis": "Rhapsis",
"legrl": "Bramble",
"legrwall": "Dragon's Constitution",
"legscout": "Wheelie",
"legsd": "Ichnaea",
"legsh": "Glaucus",
"legshot": "Phalanx",
"legsilo": "Supernova",
"legsnapper": "Snapper",
"legsolar": "Solar Collector",
"legsrail": "Arquebus",
"legsrailt4": "Epic Arquebus",
"legstarfall": "Starfall",
"legstingray":"Stingray",
"legstr": "Hoplite",
"legstronghold": "Stronghold",
"legsy": "Shipyard",
"legtarg": "Pinpointer",
"legtide": "Tidal Generator",
"legtl": "Stheno",
"legtriarius": "Triarius",
"legtriariusdrone": "Triarius",
"leguwestore": "Naval Energy Storage",
"leguwgeo": "Offshore Geothermal Powerplant",
"leguwmstore": "Naval Metal Storage",
"legvcarry": "Mantis",
"legvelite": "Velite",
"legvenator": "Venator",
"legvflak": "Charon",
"legvision": "Vision",
"legvp": "Legion Vehicle Plant",
"legwhisper": "Whisper",
"legwin": "Wind Turbine",
"legwint2": "Advanced Wind Turbine",